# Jekyll configuration for Pintwise
title: Pintwise - Pint Debt Tracker
description: Track pints owed between friends
baseurl: "/pintwise" # Change this to your repository name
url: "https://yourusername.github.io" # Change this to your GitHub username

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - webpack.*.js
  - .env
  - README.md
  - js/
  - css/
  - img/

# Include the dist folder contents
include:
  - dist/

# Plugin settings
plugins:
  - jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: false
